### ISSUE TITLE
Noob: EOS

### ISSUE THREAD

**Issue by dackdel** [M4cs/BabySploit#10]
I am running elementaryos juno. Keep getting this `W: GPG error: http://ftp.yzu.edu.tw/Linux/kali kali-rolling InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ED444FF07D8D0BF6
E: The repository 'http://http.kali.org/kali kali-rolling InRelease' is not signed.
W: Updating from such a repository can't be done securely, and is therefore disabled by default.
W: See apt-secure(8) manpage for repository creation and user configuration details.
E: http://ftp.yzu.edu.tw/Linux/kali kali-rolling InRelease is not (yet) available (The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ED444FF07D8D0BF6)` this error after I have installed babysploit and i try to run a sudo apt-get update. Noob here, bear with me.

**Comment by M4cs** [comment]
So basically it’s just having issues signing the Kali repo on apt. If you need to go to /etc/apt/sources.list and add a # before “deb http://http.kali.org....”

**Comment by dackdel** [comment]
is there a way to uninstall completely. like remove the ftp.yzu.edu.tw./Linux/kali kali-rolling from my system. cause i cant find it when i do ls -lh /etc/apt/sources.list.d

**Comment by M4cs** [comment]
Run `nano /etc/apt/sources.list` not sources.list.d. And then yeah you can just delete the line.
