### ISSUE TITLE
nmap error

### ISSUE THREAD

**Issue by bayvista** [M4cs/BabySploit#12]
nmap 192.168.1.1/24
> 1
sh: 1: cannot create ./logs/nmap_scan_2018-11-20: Directory nonexistent

**Comment by M4cs** [comment]
Try rerunning start.py. If updating doesnt work then try deleting and repulling. Latest commit should fix

**Comment by bayvista** [comment]
Still no luck. Hangs when running 'install.py'

bayvista@kali:~$ git clone git://github.com/M4cs/BabySploit ~/BabySploit
Cloning into '/home/bayvista/BabySploit'...
remote: Enumerating objects: 133, done.
remote: Counting objects: 100% (133/133), done.
remote: Compressing objects: 100% (103/103), done.
remote: Total 974 (delta 50), reused 90 (delta 24), pack-reused 841
Receiving objects: 100% (974/974), 9.03 MiB | 727.00 KiB/s, done.
Resolving deltas: 100% (399/399), done.
bayvista@kali:~$ cd BabySploit
bayvista@kali:~/BabySploit$ sudo python3 install.py
 ==  BabySploit Installation  ==
Press ENTER To Start Installation
 [09:19:10] Adding Regular Repo To Sources [1]...               [09:19:10]
Adding Regular Repo To Sources [1]...                  [STATUS] Complete
[WARNING] None
 [09:19:10] Adding Regular Repo To Sources [2]...               [09:19:10]
Adding Regular Repo To Sources [2]...                  [STATUS] Complete
[WARNING] None
 [09:19:10] Adding Source Repo To Sources  [1]...               [09:19:10]
Adding Source Repo To Sources  [1]...                  [STATUS] Complete
[WARNING] None
 [09:19:10] Adding Source Repo To Sources  [2]...               [09:19:10]
Adding Source Repo To Sources  [2]...                  [STATUS] Complete
[WARNING] None
 [09:19:10] Cleaning APT...                                     [09:19:10]
Cleaning APT...                                        [STATUS] Complete
[WARNING] None
 [09:19:10] Updating APT...                                     [09:19:10]
Updating APT...                                        [STATUS] Complete
[WARNING] None
 [09:19:21] Upgrading APT...                                    [09:19:21]
Upgrading APT...                                        [STATUS] Complete
[WARNING] None
 [09:19:23] Upgrading Dist...
[STATUS] Processing

**Comment by M4cs** [comment]
Its upgrading your distro you need to wait.

**Comment by M4cs** [comment]
The installation takes a long time if you are not on kali.

**Comment by bayvista** [comment]
After 2 hours, I gave up. I'll try Metasploit

**Comment by M4cs** [comment]
Totally different tool but good luck!
