### ISSUE TITLE
blackeye pages not working

### ISSUE THREAD

**Issue by gr3yhood** [M4cs/BabySploit#18]
Hi when i choose a page it only uses facebook and the facebook page is incomplete( missing html and css elements).

**Comment by M4cs** [comment]
Make sure you have no background PHP or Python process running in the background. Don't use the facebook site it must be broken.

**Comment by gr3yhood** [comment]
i have no other python or php processes running. also the blackeye cancels itself after 20 mins of it running. please fix

**Comment by M4cs** [comment]
Moving this to [BlackEye Python Repo](https://github.com/M4cs/BlackEye-Python) #
