### ISSUE TITLE
Unable to create ‘configuration’ path on MacOS

### ISSUE THREAD

**Issue by BlueRhino** [M4cs/BabySploit#22]
'mkdir' can not create a path recursively.Use 'mkdir -p '

**Comment by M4cs** [comment]
Thank you for your contributions! Next PR make sure to add your name to the README :)

**Comment by BlueRhino** [comment]
First of all, thank you very much for the open source project.  
I am very happy to have the opportunity to contribute code to this project. I've been using Java.I'm new to python and network security.
 I hope I can contribute to this project as well as learn something about python and network security.

**Comment by BlueRhino** [comment]
> Thank you for your contributions! Next PR make sure to add your name to the README :)

First of all, thank you very much for the open source project.  
I am very happy to have the opportunity to contribute code to this project. I've been using Java.I'm new to python and network security.
 I hope I can contribute to this project as well as learn something about python and network security.
