### ISSUE TITLE
Garbled in the terminal

### ISSUE THREAD

**Issue by BlueRhino** [M4cs/BabySploit#26]
https://github.com/M4cs/BabySploit/blob/9ee5579b57668ada6883ede8433143fc534eb325/babysploit/helper.py#L2  
Now I try to debug the code on Kali with Pycharm.  
There is garbled in the terminal.  
![screenshot from 2019-01-22 19-48-42](https://user-images.githubusercontent.com/4610694/51534287-53acee00-1e80-11e9-9904-afcd7da72e71.png)
And If I changed the 'SingleTable' to 'AsciiTable' ,The display becomes normal.

**Comment by M4cs** [comment]
That's because the SingleTable uses characters that PyCharm isn't capable of displaying.

**Comment by BlueRhino** [comment]
Is there a solution？And displays normally on Win7 and MacOS

**Comment by M4cs** [comment]
I would use a different IDE. If you need a terminal VS Code works fine iirc. If not you can switch all the SingleTables to AsciiTables while debugging.

**Comment by BlueRhino** [comment]
Ok.Do you have a plan to optimize the command line? For example, integrating python-prompt-toolkit? Maybe I can do some work in this area.

**Comment by M4cs** [comment]
Not very familiar with that library so no I didn't really have any plans for that. If you'd like to thats fine :)

**Comment by BlueRhino** [comment]
I stumbled upon a solution when I used python-prompt-toolkit.To enable the "Emulate terminal in output console" option in the *Run/Debug Configuration.
![1](https://user-images.githubusercontent.com/4610694/51889418-869d3780-23d4-11e9-8489-046423c75bb6.png)
Refer to this https://github.com/prompt-toolkit/python-prompt-toolkit/issues/404#issuecomment-421810700

**Comment by M4cs** [comment]
Safe to close i think?
