### ISSUE TITLE
Give me the credits!!

### ISSUE THREAD

**Issue by researchersource** [M4cs/BabySploit#27]

**Comment by M4cs** [comment]
Fucks sake I'm shaking my head at myself right now because I deleted the header from my original fork [here](https://github.com/M4cs/BlackEye-Python) which did credit you. My bad :( -1 rep for me

**Comment by M4cs** [comment]
Added you to the README as well. Sorry bout that.

Commit hash: f52fe9772383a95e07e017002ee27a4d47bb5d50

**Comment by thelinuxchoice** [comment]
Thank you!
