### ISSUE TITLE
Cannot find config.cfg

### ISSUE THREAD

**Issue by maginter** [M4cs/BabySploit#5]
FileNotFoundError: [Errno 2] No such file or directory: 'babysploit/config/config.cfg'

**Comment by M4cs** [comment]
Hmm the most recent commit comes with a config.cfg so it should be able to find it. If not just make a file in the config directory. You can find this directory by going to the root of babysploit and finding the babysploit folder. Create config.cfg inside the folder called config in there.

**Comment by Moonbeam4520** [comment]
I get the same error when launching babysploit from another directory. I need to cd in the babysploit dir and then lauch `start.py`

**Comment by M4cs** [comment]
The instructions tell you to do so.
