### ISSUE TITLE
Module not found 'pyfiglet'

### ISSUE THREAD

**Issue by hasangokdag** [M4cs/BabySploit#7]
`root@kali:~/BabySploit# python3 start.py 
Traceback (most recent call last):
  File "start.py", line 5, in <module>
    from pyfiglet import Figlet
ModuleNotFoundError: No module named 'pyfiglet'
`

**Comment by M4cs** [comment]
Did you run pip3 install -r requirements.txt inside the BabySploit folder?

**Comment by hasangokdag** [comment]
I tried running it in the first place and got 
`
Collecting discord.py==1.0.0a1590+g860d6a9 (from -r requirements.txt (line 23))
  Could not find a version that satisfies the requirement discord.py==1.0.0a1590+g860d6a9 (from -r requirements.txt (line 23)) (from versions: 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.9.2, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 0.16.5, 0.16.6, 0.16.7, 0.16.8, 0.16.9, 0.16.10, 0.16.11, 0.16.12)
No matching distribution found for discord.py==1.0.0a1590+g860d6a9 (from -r requirements.txt (line 23))
`

So i moved on and tried to run start.py
By the way before that point when executing
`perl MakeFile` I got
`Can't open perl script "MakeFile": No such file or directory` thus could not proceed with
`make test
sudo make install
cd ..
sudo rm -rf Image-ExifTool-11.17`

**Comment by M4cs** [comment]
Try deleting your clone and recloning. Then run `sudo python3 install.py` from within the BabySploit Directory.
