### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bayvista** [M4cs/BabySploit#9]
Having installed Babysploit, how do you start it? I've tried BabySploit and babysploit but these are rejected.

Also, I now have two directories in my Home directory
/BabySploit
/babysploit

Is this correct? Thanks

**Comment by M4cs** [comment]
Dont know why there are two folders named that in your home directory. You must not be running it from within the BabySploit directory like it says on the Readme. You probably just ran it from home. Delete both of those. Repull and refer to the Readme where it goes through getting setup.

**Comment by bayvista** [comment]
Thanks, and how do I start the program?

**Comment by M4cs** [comment]
if you cloned BabySploit to your home directory "~/" then run `cd ~/BabySploit`. After that run `sudo apt-get update` and `sudo apt-get upgrade`. Then run `sudo python3 install.py`. Then run `virtutalenv env/bin/activate`. Then run `pip3 install -r requirements.txt`. Finally run `python3 start.py`.

**Comment by jhemmmm** [comment]
doesn't work in CentOS, it was probably the last line, and it can't open the file from /etc again.

**Comment by M4cs** [comment]
As stated in the readme its made for Debian and Kali atm.

**Comment by M4cs** [comment]
Could you send me the terminal output please

**Comment by jhemmmm** [comment]
There you go.
![image](https://user-images.githubusercontent.com/14343151/48693114-5cc8d700-ec13-11e8-9aef-efd465b153c5.png)

**Comment by bayvista** [comment]
Many thanks
